src/AppBundle/Entity/OrderList.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Proxy\Exception\InvalidArgumentException;

/**
 * Class OrderList
 * @package AppBundle\Entity
 */
class OrderList
{
    /**
     * @var integer Id
     */
    protected $id;

    /**
     * @var ArrayCollection Collection of order items
     */
    protected $orderItem;

    /**
     * @var Delivery Original delivery entity - used for frontend interaction
     */
    protected $delivery;
    /**
     * @var OrderDeliveryItem Original order delivery item entity
     */
    protected $orderDeliveryItem;
    /**
     * @var Payment Original payment entity - used for frontend interaction
     */
    protected $payment;
    /**
     * @var OrderPaymentItem Original order payment item entity
     */
    protected $orderPaymentItem;
    /**
     * @var string Delivery detail - typically branch store
     */
    protected $deliveryDetail;
    /**
     * @var Discount Original discount entity - used for frontend interaction
     */
    protected $discount;
    /**
     * @var OrderDiscountItem Original order discount item entity
     */
    protected $orderDiscountItem;

    /**
     * @var string Delivery email
     */
    protected $deliveryEmail;
    /**
     * @var string Delivery first name
     */
    protected $deliveryFirstname;
    /**
     * @var string Delivery last name
     */
    protected $deliveryLastname;
    /**
     * @var string Delivery phone
     */
    protected $deliveryPhone;
    /**
     * @var string Delivery street
     */
    protected $deliveryStreet;
    /**
     * @var string Delivery city
     */
    protected $deliveryCity;
    /**
     * @var integer Delivery zip code
     */
    protected $deliveryZipCode;
    /**
     * @var string Delivery street
     */

    /**
     * @var bool Billing information are different from delivery information
     */
    protected $billingDifferent;
    /**
     * @var string Billing email
     */
    protected $billingEmail;
    /**
     * @var string Billing first name
     */
    protected $billingFirstname;
    /**
     * @var string Billing last name
     */
    protected $billingLastname;
    /**
     * @var string Billing phone
     */
    protected $billingPhone;
    /**
     * @var string Billing street
     */
    protected $billingStreet;
    /**
     * @var string Billing city
     */
    protected $billingCity;
    /**
     * @var integer Billing zip code
     */
    protected $billingZipCode;

    /**
     * @var string Remarks
     */
    protected $remarks;

    /**
     * @var \DateTime Date and time when order was created on
     */
    protected $orderCreatedOn;
    /**
     * @var \DateTime Date and time when order was received on
     */
    protected $orderReceivedOn;
    /**
     * @var \DateTime Date and time when order was sent on
     */
    protected $orderSentOn;
    /**
     * @var \DateTime Date and time when order was finished on
     */
    protected $orderFinishedOn;
    /**
     * @var \DateTime Date and time when order was canceled on
     */
    protected $orderCanceledOn;
    /**
     * @var \DateTime Date and time when order was cancel by email on
     */
    protected $emailCanceledOn;

    /**
     * @var \AppBundle\Entity\User User which order was handled by
     */
    protected $handledBy;
    /**
     * @var \DateTime Date and time when order was handled on
     */
    protected $handledOn;

    /**
     * @var bool This order list can be changed by customer
     */
    protected $active;
    /**
     * @var string Status of order (Acceptable enum values - Created|Received|Sent|Finished|Canceled)
     */
    protected $status;
    /**
     * @var bool Customer accepted terms and conditions
     */
    protected $termsAndConditions;
    /**
     * @var bool Customer accepted newsletter subscription
     */
    protected $newsletter;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->orderItem = new \Doctrine\Common\Collections\ArrayCollection();
        $this->orderCreatedOn = new \DateTime();
        $this->active = true;
        $this->status = 'Created';
        $this->termsAndConditions = false;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get order number
     *
     * @return integer
     */
    public function getOrderNumber()
    {
        return $this->orderCreatedOn->format('y') . '000' . $this->id;
    }

    /**
     * Set collection of order items
     *
     * @param ArrayCollection $orderItems
     * @return OrderList
     */
    public function setOrderItem(ArrayCollection $orderItems)
    {
        $this->orderItem = $orderItems;

        return $this;
    }

    /**
     * Get collection of order items
     *
     * @return ArrayCollection
     */
    public function getOrderItem()
    {
        return $this->orderItem;
    }

    /**
     * Add order item to collection of order items
     *
     * @param OrderItem $orderItem
     * @return OrderList
     */
    public function addOrderItem(OrderItem $orderItem)
    {
        $this->orderItem[] = $orderItem;

        return $this;
    }

    /**
     * Reset collection of order items
     *
     * @return OrderList
     */
    public function resetOrderItem()
    {
        $this->orderItem = null;

        return $this;
    }

    /**
     * Remove order item from collection of order items
     *
     * @param OrderItem $orderItem
     */
    public function removeOrderItem(OrderItem $orderItem)
    {
        $this->orderItem->removeElement($orderItem);
    }

    /**
     * Set original delivery entity - used for frontend interaction
     *
     * @param Delivery $delivery
     * @return OrderList
     */
    public function setDelivery(Delivery $delivery = null)
    {
        $this->delivery = $delivery;

        if ($delivery) {
            if ($this->orderDeliveryItem) {
                $this->orderDeliveryItem->setMethod($delivery->getMethod());
                $this->orderDeliveryItem->setFormat($delivery->getFormat());
                $this->orderDeliveryItem->setFee($delivery->getFee());
                $this->orderDeliveryItem->setDeliveryId($delivery);
            } else {
                $this->orderDeliveryItem = new OrderDeliveryItem();
                $this->orderDeliveryItem->setMethod($delivery->getMethod());
                $this->orderDeliveryItem->setFormat($delivery->getFormat());
                $this->orderDeliveryItem->setFee($delivery->getFee());
                $this->orderDeliveryItem->setDeliveryId($delivery);
            }
        }

        return $this;
    }

    /**
     * Get original delivery entity - used for frontend interaction
     *
     * @return Delivery
     */
    public function getDelivery()
    {
        if ($this->orderDeliveryItem) {
            // Backend
            if ($this->orderDeliveryItem->getDeliveryId()) {
                // If original delivery is still available
                $this->delivery = $this->orderDeliveryItem->getDeliveryId();

                return $this->delivery;
            } else {
                // If original delivery is removed
                return $this->delivery;
            }
        } else {
            // Frontend
            return $this->delivery;
        }
    }

    /**
     * Set original order delivery item entity
     *
     * @param OrderDeliveryItem $orderDeliveryItem
     * @return OrderList
     */
    public function setOrderDeliveryItem(OrderDeliveryItem $orderDeliveryItem = null)
    {
        $this->orderDeliveryItem = $orderDeliveryItem;

        return $this;
    }

    /**
     * Get original order delivery item entity
     *
     * @return \AppBundle\Entity\OrderDeliveryItem
     */
    public function getOrderDeliveryItem()
    {
        return $this->orderDeliveryItem;
    }

    /**
     * Set delivery detail - typically branch store
     *
     * @param string $deliveryDetail
     * @return OrderList
     */
    public function setDeliveryDetail($deliveryDetail)
    {
        $this->deliveryDetail = $deliveryDetail;

        return $this;
    }

    /**
     * Get delivery detail - typically branch store
     *
     * @return string
     */
    public function getDeliveryDetail()
    {
        return $this->deliveryDetail;
    }

    /**
     * Set original payment entity - used for frontend interaction
     *
     * @param Payment $payment
     * @return OrderList
     */
    public function setPayment(Payment $payment = null)
    {
        $this->payment = $payment;

        if ($payment) {
            if ($this->orderPaymentItem) {
                $this->orderPaymentItem->setMethod($payment->getMethod());
                $this->orderPaymentItem->setFee($payment->getFee());
                $this->orderPaymentItem->setPaymentId($payment);
            } else {
                $this->orderPaymentItem = new OrderPaymentItem();
                $this->orderPaymentItem->setMethod($payment->getMethod());
                $this->orderPaymentItem->setFee($payment->getFee());
                $this->orderPaymentItem->setPaymentId($payment);
            }
        }

        return $this;
    }

    /**
     * Get original payment entity - used for frontend interaction
     *
     * @return Payment
     */
    public function getPayment()
    {
        if ($this->orderPaymentItem) {
            // Backend
            if ($this->orderPaymentItem->getPaymentId()) {
                // If original payment is still available
                $this->payment = $this->orderPaymentItem->getPaymentId();

                return $this->payment;
            } else {
                // If original payment is removed
                return $this->payment;
            }
        } else {
            // Frontend
            return $this->payment;
        }
    }

    /**
     * Set original order payment item entity

src/AppBundle/Controller/Back/ArticleController.php
<?php

namespace AppBundle\Controller\Back;

use AppBundle\Form\Type\ArticleType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Class ArticleController
 * @package AppBundle\Controller\Back
 */
class ArticleController extends Controller
{
    /**
     * List all articles
     *
     * @return Response
     */
    public function listAction()
    {
        $articleManager = $this->get('app.article');
        $articles = $articleManager->findAll();

        return $this->render(
            'AppBundle:Back\Article:list.html.twig',
            ['articles' => $articles]
        );
    }

    /**
     * Add new article
     *
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function addAction(Request $request)
    {
        $articleManager = $this->get('app.article');
        $article = $articleManager->initialize();

        $form = $this->createForm(
            new ArticleType(),
            $article
        );
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $articleManager->add($article);

            $this->addFlash('success', 'Článek byl úspěšně přidán.');
            return $this->redirectToRoute('back_article_list');
        }

        return $this->render(
            'AppBundle:Back\Article:add.html.twig',
            ['form' => $form->createView()]
        );
    }

    /**
     * Edit existing article
     *
     * @param Request $request
     * @param $id
     * @return RedirectResponse|Response
     */
    public function editAction(Request $request, $id)
    {
        $articleManager = $this->get('app.article');
        $article = $articleManager->findById($id);

        if (!$article) {
            $this->addFlash('error', 'Článek nebyl nalezen.');
            return $this->redirectToRoute('back_article_list');
        }

        $form = $this->createForm(
            new ArticleType(),
            $article,
            ['edit_action' => true]
        );
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $articleManager->edit($article);

            $this->addFlash('success', 'Článek byl úspěšně upraven.');
            return $this->redirectToRoute('back_article_edit', ['id' => $id]);
        }

        return $this->render(
            'AppBundle:Back\Article:edit.html.twig',
            ['form' => $form->createView()]
        );
    }

    /**
     * Mark existing article as default and unmark another default articles
     *
     * @param $id
     * @return RedirectResponse
     */
    public function markDefaultAction($id)
    {
        $articleManager = $this->get('app.article');
        $article = $articleManager->findById($id);

        if (!$article) {
            $this->addFlash('error', 'Článek nebyl nalezen.');
            return $this->redirectToRoute('back_article_list');
        }

        $articleManager->markDefault($article);

        $this->addFlash('success', 'Článek byl označen jako hlavní.');
        return $this->redirectToRoute('back_article_list');
    }

    /**
     * Unmark existing article as default
     *
     * @param $id
     * @return RedirectResponse
     */
    public function unmarkDefaultAction($id)
    {
        $articleManager = $this->get('app.article');
        $article = $articleManager->findById($id);

        if (!$article) {
            $this->addFlash('error', 'Článek nebyl nalezen.');
            return $this->redirectToRoute('back_article_list');
        }

        $articleManager->unmarkDefault($article);

        $this->addFlash('success', 'Článek byl označen jako normální.');
        return $this->redirectToRoute('back_article_list');
    }

    /**
     * Remove existing article
     *
     * @param $id
     * @return RedirectResponse
     */
    public function removeAction($id)
    {
        $articleManager = $this->get('app.article');
        $article = $articleManager->findById($id);

        if (!$article) {
            $this->addFlash('error', 'Článek nebyl nalezen.');
            return $this->redirectToRoute('back_article_list');
        }

        $articleManager->remove($article);

        $this->addFlash('success', 'Článek byl úspěšně odstraněn.');
        return $this->redirectToRoute('back_article_list');

    }
}

src/AppBundle/Controller/Back/DashboardController.php
<?php

namespace AppBundle\Controller\Back;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

/**
 * Class DashboardController
 * @package AppBundle\Controller\Back
 */
class DashboardController extends Controller
{
    /**
     * Show dashboard
     *
     * @return Response
     */
    public function dashboardAction()
    {
        $orderManager = $this->get('app.order');
        $createdOrders = $orderManager->findOrdersCreated();
        $receivedOrders = $orderManager->findOrdersReceived();
        $sentOrders = $orderManager->findOrdersSent();
        $finishedOrders = $orderManager->findOrdersFinished();

        return $this->render(
            'AppBundle:Back\Dashboard:dashboard.html.twig',
            [
                'createdOrders' => $createdOrders,
                'receivedOrders' => $receivedOrders,
                'sentOrders' => $sentOrders,
                'finishedOrders' => $finishedOrders ,
                'ordersCountThisMonth' => $orderManager->ordersOpenedCountThisMonth(),
                'ordersTotalTurnoverThisMonth' => $orderManager->ordersTotalTurnoverThisMonth(),
                'ordersAverageTurnoverThisMonth' => $orderManager->ordersAverageTurnoverThisMonth(),
                'ordersCount' => $orderManager->ordersOpenedCount(),
                'ordersTotalTurnover' => $orderManager->ordersTotalTurnover(),
                'ordersAverageTurnover' => $orderManager->ordersAverageTurnover()
            ]
        );
    }
}

src/AppBundle/Controller/Back/NewsletterController.php
<?php

namespace AppBundle\Controller\Back;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Class NewsletterController
 * @package AppBundle\Controller\Back
 */
class NewsletterController extends Controller
{
    /**
     * Export existing newsletter addresses
     *
     * @return StreamedResponse
     */
    public function exportAction()
    {
        $response = new StreamedResponse();
        $response->setCallback(function () {
            $newsletterManager = $this->get('app.newsletter');
            $newsletters = $newsletterManager->findAll();

            $handle = fopen('php://output', 'w+');

            foreach ($newsletters as $newsletter) {
                fputcsv($handle, [
                    $newsletter->getEmail(),
                    $newsletter->getAddedOn()->format('Y-m-d H:i'),
                    $newsletterManager->encodeEmail($newsletter->getEmail())
                ]);
            }

            fclose($handle);
        });

        $response->setStatusCode(200);
        $response->headers->set('Content-Type', 'text/csv; charset=utf-8');
        $response->headers->set('Content-Disposition', 'attachment; filename="newsletters.csv"');

        return $response;
    }
}

src/AppBundle/Resources/views/Back/Dashboard/dashboard.html.twig
{% extends 'AppBundle:Back:layout.html.twig' %}

{% block headerTitle %}
    Přehled
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-stats icon-offset icon-vertically-aligned"
                              aria-hidden="true"></span>
                        Statistiky obchodu
                    </h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th class="col-xs-6">Poslední měsíc</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>Počet objednávek</td>
                                        <td class="text-right">{{ ordersCountThisMonth }}</td>
                                    </tr>
                                    <tr>
                                        <td>Průměrná výše objednávky</td>
                                        <td class="text-right">{{ ordersAverageTurnoverThisMonth | number_format(2, ',', '') }} Kč</td>
                                    </tr>
                                    <tr>
                                        <td>Obrat</td>
                                        <td class="text-right">{{ ordersTotalTurnoverThisMonth | number_format(2, ',', '') }} Kč</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th class="col-xs-6">Celkem</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>Počet objednávek</td>
                                        <td class="text-right">{{ ordersCount }}</td>
                                    </tr>
                                    <tr>
                                        <td>Průměrná výše objednávky</td>
                                        <td class="text-right">{{ ordersAverageTurnover | number_format(2, ',', '') }} Kč</td>
                                    </tr>
                                    <tr>
                                        <td>Obrat</td>
                                        <td class="text-right">{{ ordersTotalTurnover | number_format(2, ',', '') }} Kč</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-6">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-list icon-offset icon-vertically-aligned"
                              aria-hidden="true"></span>
                        Vytvořené objednávky
                        <span class="badge pull-right">{{ createdOrders | length }}</span>
                    </h3>
                </div>
                <div class="panel-body">

                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th class="col-xs-2">Číslo</th>
                                <th class="col-xs-8">Zákazník</th>
                                <th class="text-nowrap text-right">Vytvořeno</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for createdOrder in createdOrders %}
                                <tr>
                                    <td>
                                        <a href="{{ path('back_order_show', {'id' : createdOrder.id}) }}" title="Zobrazit objednávku">
                                            {{ createdOrder.orderNumber  }}
                                        </a>
                                    </td>
                                    <td>
                                        {{ createdOrder.deliveryFirstname }} {{ createdOrder.deliveryLastname }}
                                    </td>
                                    <td class="text-nowrap text-right">
                                        {{ createdOrder.orderCreatedOn | date("Y-m-d H:i") }}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

        </div>
        <div class="col-md-6">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-list icon-offset icon-vertically-aligned"
                              aria-hidden="true"></span>
                        Přijaté objednávky
                        <span class="badge pull-right">{{ receivedOrders | length }}</span>
                    </h3>
                </div>
                <div class="panel-body">

                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th class="col-xs-2">Číslo</th>
                                <th class="col-xs-8">Zákazník</th>
                                <th class="text-nowrap text-right">Přijato</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for receivedOrder in receivedOrders %}
                                <tr>
                                    <td>
                                        <a href="{{ path('back_order_show', {'id' : receivedOrder.id}) }}" title="Zobrazit objednávku">
                                            {{ receivedOrder.orderNumber  }}
                                        </a>
                                    </td>
                                    <td>
                                        {{ receivedOrder.deliveryFirstname }} {{ receivedOrder.deliveryLastname }}
                                    </td>
                                    <td class="text-nowrap text-right">
                                        {{ receivedOrder.orderReceivedOn | date("Y-m-d H:i") }}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

        </div>
        <div class="col-md-6">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-list icon-offset icon-vertically-aligned"
                              aria-hidden="true"></span>
                        Odeslané objednávky
                        <span class="badge pull-right">{{ sentOrders | length }}</span>
                    </h3>
                </div>
                <div class="panel-body">

                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th class="col-xs-2">Číslo</th>
                                <th class="col-xs-8">Zákazník</th>
                                <th class="text-nowrap text-right">Odesláno</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for sentOrder in sentOrders %}
                                <tr>
                                    <td>
                                        <a href="{{ path('back_order_show', {'id' : sentOrder.id}) }}" title="Zobrazit objednávku">
                                            {{ sentOrder.orderNumber  }}
                                        </a>
                                    </td>
                                    <td>
                                        {{ sentOrder.deliveryFirstname }} {{ sentOrder.deliveryLastname }}
                                    </td>
                                    <td class="text-nowrap text-right">
                                        {{ sentOrder.orderReceivedOn | date("Y-m-d H:i") }}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

        </div>
        <div class="col-md-6">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-list icon-offset icon-vertically-aligned"
                              aria-hidden="true"></span>
                        Dokončené objednávky
                        <span class="badge pull-right">{{ finishedOrders | length }}</span>
                    </h3>
                </div>
                <div class="panel-body">

                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th class="col-xs-2">Číslo</th>
                                <th class="col-xs-8">Zákazník</th>
                                <th class="text-nowrap text-right">Dokončeno</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for finishedOrder in finishedOrders %}
                                <tr>
                                    <td>
                                        <a href="{{ path('back_order_show', {'id' : finishedOrder.id}) }}" title="Zobrazit objednávku">
                                            {{ finishedOrder.orderNumber  }}
                                        </a>
                                    </td>
                                    <td>
                                        {{ finishedOrder.deliveryFirstname }} {{ finishedOrder.deliveryLastname }}
                                    </td>
                                    <td class="text-nowrap text-right">
                                        {{ finishedOrder.orderCreatedOn | date("Y-m-d H:i") }}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

        </div>
    </div>

{% endblock %}