src/AppBundle/Entity/Product.php
<?php

namespace AppBundle\Entity;

use Gregwar\Image\Image;
use Symfony\Component\Debug\Exception\ContextErrorException;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Class Product
 * @package AppBundle\Entity
 */
class Product
{
    /**
     * @var integer Id of product
     */
    protected $id;
    /**
     * @var string Title of product
     */
    protected $title;
    /**
     * @var string Alias of product
     */
    protected $alias;
    /**
     * @var string Description of product
     */
    protected $description;
    /**
     * @var integer Price of product
     */
    protected $price;
    /**
     * @var integer Quantity of product
     */
    protected $quantity;
    /**
     * @var integer Discount of product
     */
    protected $discount;
    /**
     * @var integer Count (amount) of pieces of product
     */
    protected $count;
    /**
     * @var CountText Original count text entity - Text suffix to count (amount) of pieces of product
     */
    protected $countText;
    /**
     * @var \DateTime Date and time when product was written on
     */
    protected $writtenOn;
    /**
     * @var \AppBundle\Entity\User User which product was written by
     */
    protected $writtenBy;
    /**
     * @var  \DateTime Date and time when product was edited on
     */
    protected $editedOn;
    /**
     * @var \AppBundle\Entity\User User which product was edited by
     */
    protected $editedBy;
    /**
     * @var \Doctrine\Common\Collections\ArrayCollection Category in which product is
     */
    protected $category;
    /**
     * @var bool This product is marked as favourite
     */
    protected $favourite;
    /**
     * @var UploadedFile Product image file during upload
     */
    protected $file;
    /**
     * @var string Extension of product image
     */
    protected $extension;
    /**
     * @var string Temporary path to product image file during upload
     */
    protected $temp;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->category = new \Doctrine\Common\Collections\ArrayCollection();
        $this->favourite = false;
    }

    /**
     * Get id of product
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title of product
     *
     * @param string $title
     * @return Product
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title of product
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set alias of product
     *
     * @param string $alias
     * @return Product
     */
    public function setAlias($alias)
    {
        $this->alias = $alias;

        return $this;
    }

    /**
     * Get alias of product
     *
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Set description of product
     *
     * @param string $description
     * @return Product
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description of product
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set price of product
     *
     * @param integer $price
     * @return Product
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price of product
     *
     * @return integer
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Get total price of product
     *
     * @return integer
     */
    public function getTotalPrice()
    {
        if ($this->getDiscount()) {
            return $this->getPrice() * ((100 - $this->getDiscount()) / 100);
        } else {
            return $this->getPrice();
        }
    }

    /**
     * Set quantity of product
     *
     * @param integer $quantity
     * @return Product
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * Increase quantity of product
     *
     * @param integer $quantity
     * @return Product
     */
    public function increaseQuantity($quantity)
    {
        $this->quantity += $quantity;

        return $this;
    }

    /**
     * Decrease quantity of product
     *
     * @param integer $quantity
     * @return Product
     */
    public function decreaseQuantity($quantity)
    {
        $this->quantity -= $quantity;

        return $this;
    }

    /**
     * Get quantity of product
     *
     * @return integer
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Set discount of product
     *
     * @param integer $discount
     * @return Product
     */
    public function setDiscount($discount)
    {
        $this->discount = $discount;

        return $this;
    }

    /**
     * Get discount of product
     *
     * @return integer
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     * Set count (amount) of pieces of product
     *
     * @param integer $count
     * @return Product
     */
    public function setCount($count)
    {
        $this->count = $count;

        return $this;
    }

    /**
     * Get count (amount) of pieces of product
     *
     * @return integer
     */
    public function getCount()
    {
        return $this->count;
    }


    /**
     * Set countText
     *
     * @param CountText $countText
     * @return Product
     */
    public function setCountText(CountText $countText)
    {
        $this->countText = $countText;

        return $this;
    }

    /**
     * Get countText
     *
     * @return CountText
     */
    public function getCountText()
    {
        return $this->countText;
    }

    /**
     * Set date and time when product was written on
     *
     * @param \DateTime $writtenOn
     * @return Product
     */
    public function setWrittenOn($writtenOn)
    {
        $this->writtenOn = $writtenOn;

        return $this;
    }

    /**
     * Get date and time when product was written on
     *
     * @return \DateTime
     */
    public function getWrittenOn()
    {
        return $this->writtenOn;
    }

    /**
     * Set user which product was written by
     *
     * @param \DateTime $editedOn
     * @return Product
     */
    public function setEditedOn($editedOn)
    {
        $this->editedOn = $editedOn;

        return $this;
    }

    /**
     * Get user which product was written by
     *
     * @return \DateTime
     */
    public function getEditedOn()
    {
        return $this->editedOn;
    }

    /**
     * Set date and time when product was edited on
     *
     * @param \AppBundle\Entity\User $writtenBy
     * @return Product
     */
    public function setWrittenBy(\AppBundle\Entity\User $writtenBy)
    {
        $this->writtenBy = $writtenBy;

        return $this;
    }

    /**
     * Get date and time when product was edited on
     *
     * @return \AppBundle\Entity\User
     */
    public function getWrittenBy()
    {
        return $this->writtenBy;
    }

    /**
     * Set user which product was edited by
     *
     * @param \AppBundle\Entity\User $editedBy
     * @return Product
     */
    public function setEditedBy(\AppBundle\Entity\User $editedBy = null)
    {
        $this->editedBy = $editedBy;

        return $this;
    }

    /**
     * Get user which product was edited by
     *
     * @return \AppBundle\Entity\User
     */
    public function getEditedBy()
    {
        return $this->editedBy;
    }

    /**
     * Add category in which product is
     *
     * @param ProductCategory $category
     * @return Product
     */
    public function addCategory(ProductCategory $category)
    {
        $this->category[] = $category;

        return $this;
    }

    /**
     * Remove category in which product is
     *
     * @param ProductCategory $category
     */
    public function removeCategory(ProductCategory $category)
    {
        $this->category->removeElement($category);
    }

    /**
     * Set category in which product is
     *
     * @param ProductCategory $category
     * @return Product
     */
    public function setCategory(ProductCategory $category)
    {
        // Set only first category - Collection is used because of future extensibility
        $this->category = [];
        $this->category[] = $category;

        return $this;
    }

    /**
     * Get category in which product is
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCategory()
    {
        // Get only first category - Collection is used because of future extensibility
        return $this->category[0];
    }

    /**
     * Set file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
        // check if we have an old image path
        if (is_file($this->getAbsolutePath())) {
            // store the old name to delete after the update
            $this->temp = $this->getAbsolutePath();
        } else {
            $this->extension = 'initial';
        }
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Guess extension of file.
     */
    public function preUpload()
    {
        if (null !== $this->getFile()) {
            $this->extension = $this->getFile()->guessExtension();
        }
    }

    /**
     * Upload product image file
     */
    public function upload()
    {
        if (null === $this->getFile()) {
            return;
        }

src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use FOS\UserBundle\Entity\User as BaseUser;
use FOS\UserBundle\Model\GroupInterface as GroupInterface;

/**
 * Class User
 * @package AppBundle\Entity
 */
class User extends BaseUser
{
    /**
     * @var integer Id of user
     */
    protected $id;
    /**
     * @var string First name of user
     */
    protected $firstname;
    /**
     * @var string Last name of user
     */
    protected $lastname;
    /**
     * @var GroupInterface Groups of user
     */
    protected $groups;
    /**
     * @var \DateTime Date and time when user was registered at
     */
    protected $registeredAt;

    /**
     * Constructor
     */
    public function __construct()
    {
        parent::__construct();

        $this->roles = ['ROLE_USER'];
        $this->enabled = true;
        $this->registeredAt = new \DateTime();
    }

    /**
     * Get id of user
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set first name of user
     *
     * @param string $firstname
     * @return User
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get first name of user
     *
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set last name of user
     *
     * @param string $lastname
     * @return User
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get last name of user
     *
     * @return string
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * Get full name of user
     *
     * @return string
     */
    public function getFullname()
    {
        return $this->getFirstname() . ' ' . $this->getLastname();
    }

    /**
     * Set date and time when user was registered at
     *
     * @param \DateTime $registeredAt
     * @return User
     */
    public function setRegisteredAt($registeredAt)
    {
        $this->registeredAt = $registeredAt;

        return $this;
    }

    /**
     * Get date and time when user was registered at
     *
     * @return \DateTime
     */
    public function getRegisteredAt()
    {
        return $this->registeredAt;
    }

    /**
     * Add groups of user
     *
     * @param \FOS\UserBundle\Model\GroupInterface $groups
     * @return User
     */
    public function addGroup(GroupInterface $groups)
    {
        $this->groups[] = $groups;

        return $this;
    }

    /**
     * Remove groups of user
     *
     * @param \FOS\UserBundle\Model\GroupInterface $groups
     * @return null
     */
    public function removeGroup(GroupInterface $groups)
    {
        $this->groups->removeElement($groups);
    }

    /**
     * Set groups of user
     *
     * @param \FOS\UserBundle\Model\GroupInterface $groups
     * @return User
     */
    public function setGroups($groups)
    {
        $this->groups = [];
        $this->groups[] = $groups;

        return $this;
    }

    /**
     * Get groups of user
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * Set roles of user
     *
     * @param array $roles
     * @return User
     */
    public function setRoles(array $roles)
    {
        $this->roles = [];
        $this->roles[] = array_shift($this->groups->getRoles());

        return $this;
    }
}

src/AppBundle/Controller/Back/DashboardController.php
<?php

namespace AppBundle\Controller\Back;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

/**
 * Class DashboardController
 * @package AppBundle\Controller\Back
 */
class DashboardController extends Controller
{
    /**
     * Show dashboard
     *
     * @return Response
     */
    public function dashboardAction()
    {
        $orderManager = $this->get('app.order');
        $createdOrders = $orderManager->findOrdersCreated();
        $receivedOrders = $orderManager->findOrdersReceived();
        $sentOrders = $orderManager->findOrdersSent();
        $finishedOrders = $orderManager->findOrdersFinished();

        return $this->render(
            'AppBundle:Back\Dashboard:dashboard.html.twig',
            [
                'createdOrders' => $createdOrders,
                'receivedOrders' => $receivedOrders,
                'sentOrders' => $sentOrders,
                'finishedOrders' => $finishedOrders ,
                'ordersCountThisMonth' => $orderManager->ordersOpenedCountThisMonth(),
                'ordersTotalTurnoverThisMonth' => $orderManager->ordersTotalTurnoverThisMonth(),
                'ordersAverageTurnoverThisMonth' => $orderManager->ordersAverageTurnoverThisMonth(),
                'ordersCount' => $orderManager->ordersOpenedCount(),
                'ordersTotalTurnover' => $orderManager->ordersTotalTurnover(),
                'ordersAverageTurnover' => $orderManager->ordersAverageTurnover()
            ]
        );
    }
}

src/AppBundle/Controller/Back/NewsletterController.php
<?php

namespace AppBundle\Controller\Back;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Class NewsletterController
 * @package AppBundle\Controller\Back
 */
class NewsletterController extends Controller
{
    /**
     * Export existing newsletter addresses
     *
     * @return StreamedResponse
     */
    public function exportAction()
    {
        $response = new StreamedResponse();
        $response->setCallback(function () {
            $newsletterManager = $this->get('app.newsletter');
            $newsletters = $newsletterManager->findAll();

            $handle = fopen('php://output', 'w+');

            foreach ($newsletters as $newsletter) {
                fputcsv($handle, [
                    $newsletter->getEmail(),
                    $newsletter->getAddedOn()->format('Y-m-d H:i'),
                    $newsletterManager->encodeEmail($newsletter->getEmail())
                ]);
            }

            fclose($handle);
        });

        $response->setStatusCode(200);
        $response->headers->set('Content-Type', 'text/csv; charset=utf-8');
        $response->headers->set('Content-Disposition', 'attachment; filename="newsletters.csv"');

        return $response;
    }
}

src/AppBundle/Controller/Back/SortingController.php
<?php

namespace AppBundle\Controller\Back;

use AppBundle\Form\Type\SortingType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Class SortingController
 * @package AppBundle\Controller\Back
 */
class SortingController extends Controller
{
    /**
     * List sorting table
     *
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function listAction(Request $request)
    {
        $sortingManager = $this->get('app.sorting');
        $sorting = $sortingManager->findAll();

        $form = $this->createForm(
            new SortingType()
        );

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $data = json_decode($form->getData()['data']);
            $sortingManager->changeSorting($data);

            $this->addFlash('success', 'Řazení bylo úspěsně uloženo.');
            return $this->redirectToRoute('back_sorting_list');
        }

        return $this->render(
            'AppBundle:Back\Sorting:list.html.twig',
            [
                'form' => $form->createView(),
                'sorting' => $sorting
            ]
        );
    }
}

src/AppBundle/Resources/views/Back/Order/list.html.twig
{% extends 'AppBundle:Back:layout.html.twig' %}

{% block headerTitle %}
    Objednávky
{% endblock %}

{% block headerAction %}
    <a href="{{ path('back_order_export') }}" class="btn btn-primary cta">
        <span class="glyphicon glyphicon-export"></span>
        Exportovat objednávky
    </a>
{% endblock %}

{% block body %}
    <table class="table article-list" data-pagination="25">
        <thead>
        <tr>
            <th class="table-cell-id sorting-asc" data-toggle="sort" tabindex="1">Číslo</th>
            <th data-toggle="sort" tabindex="2">Jméno a příjmení</th>
            <th data-toggle="sort" tabindex="3">Cena</th>
            <th data-toggle="sort" tabindex="4">Stav</th>
            <th data-toggle="sort" tabindex="5">Zpracováno</th>
            <th data-toggle="sort" tabindex="6">Zpracoval</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td class="table-cell-id">{{ order.getOrderNumber }}</td>
                <td class="table-cell">{{ order.deliveryFirstname ~ ' ' ~ order.deliveryLastname }}</td>
                <td class="table-cell" data-sort-value="{{ zerofill(order.getTotalPrice | number_format(2, '.', ''), 8, 0) }}">{{ order.getTotalPrice | number_format(2, '.', '') }} Kč</td>
                <td class="table-cell">{{ order.status | trans }}</td>
                {% if order.handledOn %}
                    <td class="table-cell">{{ order.handledOn | date("Y-m-d H:i") }}</td>
                {% else %}
                    <td class="table-cell">-</td>
                {% endif %}
                <td class="table-cell">{{ order.handledBy.fullname | default('-') }}</td>
                <td class="table-cell-actions">
                    <a href="{{ path('back_order_show', {'id' : order.id}) }}" class="item-action" title="Zobrazit objednávku">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                </td>
            </tr>
        {%  endfor %}
        </tbody>
    </table>
    <nav data-pagination-nav="true">
    </nav>
{% endblock %}

src/AppBundle/Resources/views/Back/Order/show.html.twig
{% extends 'AppBundle:Back:layout.html.twig' %}

{% block headerTitle %}
    Zobrazit objednávku
{% endblock %}

{% set narrowBody = true %}

{% block body %}
            {{ form_start(form) }}

            <h2>Dodací údaje</h2>
            <hr>
            {{ form_row(form.deliveryFirstname) }}
            {{ form_row(form.deliveryLastname   ) }}
            {{ form_row(form.deliveryStreet) }}
            {{ form_row(form.deliveryCity) }}
            {{ form_row(form.deliveryZipCode) }}
            {{ form_row(form.deliveryEmail) }}
            {{ form_row(form.deliveryPhone) }}
            {{ form_row(form.remarks) }}

            <h2>Fakturační údaje</h2>
            <hr>
            {{ form_row(form.billingDifferent) }}
            {{ form_row(form.billingFirstname) }}
            {{ form_row(form.billingLastname) }}
            {{ form_row(form.billingStreet) }}
            {{ form_row(form.billingCity) }}
            {{ form_row(form.billingZipCode) }}
            {{ form_row(form.billingEmail) }}
            {{ form_row(form.billingPhone) }}

            <h2>Doprava a platba</h2>
            <hr>
            {{ form_row(form.delivery) }}
            {{ form_row(form.deliveryDetail) }}
            {{ form_row(form.payment) }}

            <h2>Sleva</h2>
            <hr>
            {{ form_row(form.discount) }}

            <h2>Časový přehled</h2>
            <hr/>
            <div class="form-group">
                <label>Vytvořena dne</label>
                <input type="text" class="form-control" disabled="disabled" value="{% if form.vars.data.orderCreatedOn %}{{ form.vars.data.orderCreatedOn | date("Y-m-d H:i") }}{% endif %}">
            </div>
            <div class="form-group">
                <label>Potvrzena dne</label>
                <input type="text" class="form-control" disabled="disabled" value="{% if form.vars.data.orderReceivedOn %}{{ form.vars.data.orderReceivedOn | date("Y-m-d H:i") }}{% endif %}">
            </div>
            <div class="form-group">
                <label>Odeslána dne</label>
                <input type="text" class="form-control" disabled="disabled" value="{% if form.vars.data.orderSentOn %}{{ form.vars.data.orderSentOn | date("Y-m-d H:i") }}{% endif %}">
            </div>
            <div class="form-group">
                <label>Dokončena dne</label>
                <input type="text" class="form-control" disabled="disabled" value="{% if form.vars.data.orderFinishedOn %}{{ form.vars.data.orderFinishedOn | date("Y-m-d H:i") }}{% endif %}">
            </div>
            <div class="form-group">
                <label>Stornována dne</label>
                <input type="text" class="form-control" disabled="disabled" value="{% if form.vars.data.orderCanceledOn %}{{ form.vars.data.orderCanceledOn | date("Y-m-d H:i") }}{% endif %}{% if form.vars.data.emailCanceledOn %} (Stornováno emailem){% endif %}">
            </div>

            <h2>Stav objednávky</h2>
            <hr/>

            {{ form_row(form.active) }}
            {{ form_row(form.status) }}

            {% if form.status.vars.value == 'Created' %}
                <div class="form-group">
                    <a href="{{ path('back_order_change_status', {id: form.vars.data.id, status: 'Received'}) }}" class="btn btn-success btn-block">
                        Přijmout
                    </a>
                </div>
                <div class="form-group">
                    <a href="{{ path('back_order_change_status', {id: form.vars.data.id, status: 'Canceled'}) }}" class="btn btn-danger btn-block">
                        Stornovat
                    </a>
                </div>
            {% elseif form.status.vars.value == 'Received' %}
                <div class="form-group">
                    <a href="{{ path('back_order_change_status', {id: form.vars.data.id, status: 'Sent'}) }}" class="btn btn-success btn-block">
                        Odeslat
                    </a>
                </div>
                <div class="form-group">
                    <a href="{{ path('back_order_change_status', {id: form.vars.data.id, status: 'Canceled'}) }}" class="btn btn-danger btn-block">
                        Stornovat
                    </a>
                </div>
            {% elseif form.status.vars.value == 'Sent' %}
                <div class="form-group">
                    <a href="{{ path('back_order_change_status', {id: form.vars.data.id, status: 'Finished'}) }}" class="btn btn-success btn-block">
                        Dokončit
                    </a>
                </div>
                <div class="form-group">
                    <a href="{{ path('back_order_change_status', {id: form.vars.data.id, status: 'Canceled'}) }}" class="btn btn-danger btn-block">
                        Stornovat
                    </a>
                </div>
                <div class="form-group">
                    <a href="{{ path('back_order_invoice', {orderNumber: form.vars.data.getOrderNumber}) }}" class="btn btn-primary btn-block">
                        Zobrazit fakturu
                    </a>
                </div>
            {% elseif form.status.vars.value == 'Finished' %}
                <div class="form-group">
                    <a href="{{ path('back_order_change_status', {id: form.vars.data.id, status: 'Canceled'}) }}" class="btn btn-danger btn-block">
                        Stornovat
                    </a>
                </div>
                <div class="form-group">
                    <a href="{{ path('back_order_invoice', {orderNumber: form.vars.data.getOrderNumber}) }}" class="btn btn-primary btn-block">
                        Zobrazit fakturu
                    </a>
                </div>
            {% elseif form.status.vars.value == 'Canceled' %}
            {% endif %}

            {{ form_row(form.add) }}
            {{ form_end(form) }}

        </div>
    </div>

    <div class="offset-bottom-larger"></div>

    <h2>Položky objednávky {{ form.vars.data.getOrderNumber }}</h2>
    <hr>
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th data-toggle="sort" tabindex="2">Produkt</th>
                <th data-toggle="sort" tabindex="2">Cena za kus</th>
                <th data-toggle="sort" tabindex="2">Počet kusů</th>
                <th data-toggle="sort" tabindex="2">Sleva</th>
                <th data-toggle="sort" tabindex="2">Cena celkem</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
                {% for orderItem in orderItems %}
                    <tr>
                        {% if orderItem.product != null %}
                            <td><a href="{{ path('back_product_edit', {id: orderItem.product.id}) }}">{{ orderItem.title }}</a></td>
                        {% else %}
                            <td>{{ orderItem.title }}</td>
                        {% endif %}
                        <td>{{ orderItem.price | number_format(2, '.', '') }} Kč</td>
                        <td>{{ orderItem.quantity }} ks</td>
                        <td>{{ orderItem.discount }} %</td>
                        <td>{{ orderItem.totalPrice | number_format(2, '.', '') }} Kč</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td>Doprava: {{ form.vars.data.orderDeliveryItem.method }}</td>
                    <td>{{ form.vars.data.orderDeliveryItem.fee| number_format(2, '.', '') }} Kč</td>
                    <td>1 ks</td>
                    <td>0 %</td>
                    <td>{{ form.vars.data.orderDeliveryItem.fee | number_format(2, '.', '') }} Kč</td>
                </tr>
                <tr>
                    <td>Platba: {{ form.vars.data.orderPaymentItem.method }}</td>
                    <td>{{ form.vars.data.orderPaymentItem.fee | number_format(2, '.', '') }} Kč</td>
                    <td>1 ks</td>
                    <td>0 %</td>
                    <td>{{ form.vars.data.orderPaymentItem.fee | number_format(2, '.', '') }} Kč</td>
                </tr>
            </tbody>
            <tfoot class="tfoot-separated">
                <tr>
                    <th colspan="3"></th>
                    <th>Sleva:</th>
                    <th>{{ form.vars.data.orderDiscountItem.discount | default(0) }} %</th>
                </tr>
                <tr>
                    <th colspan="3"></th>
                    <th>Cena bez slevy:</th>
                    <th>{{ form.vars.data.getTotalPriceWithoutDiscount | number_format(2, '.', '') }} Kč</th>
                </tr>
                <tr>
                    <th colspan="3"></th>
                    <th>Cena celkem:</th>
                    <th>{{ form.vars.data.getTotalPrice | number_format(2, '.', '') }} Kč</th>
                </tr>
            </tfoot>
        </table>
    </div>

    <div class="row">
        <div class="col-lg-7 col-md-9 col-sm-11 col-xs-12 col-center-block">

{% endblock %}